DELETE http://localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphdGluc2luc2FkNzFzMEBnbWFpbC5jb20iLCJleHAiOjE3NjY2MTMwNDQsInVzZXJJZCI6MX0.MyV7Gx_czgnpAuaFB8B5DpmLaXx9BdAKiuOVqrRN9jg